number = @{ int }
int = { ("+" | "-")? ~ ASCII_DIGIT+ }
op = _{"+" | "-" | "*" | "/" | "%" | "^" | ("<" | ">" | "=" | "!") ~ ("=")? | "!" | "||" | "&&"}
symbol = @{op | "&" | "\\" | "_" | (ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_" | "-")*) }
expr = _{ number | symbol | sexpr | qexpr }
sexpr = { "(" ~ expr* ~ ")" }
qexpr = { "{" ~ expr* ~ "}" }
lispy = _{ SOI ~ expr+ ~ EOI }
WHITESPACE = _{ " " | "\t" }